-d E:\Projects\Electronics\VLSI\FPGA\tang_nano_9k\tn9k_digital_clock\impl\gwsynthesis\tn9k_digital_clock.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\Projects\Electronics\VLSI\FPGA\tang_nano_9k\tn9k_digital_clock\src\tn9k_digital_clock.cst
-cfg E:\Projects\Electronics\VLSI\FPGA\tang_nano_9k\tn9k_digital_clock\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
